title: [Ley de Amnistía]
description: [Ley de Amnistía emitida por la Asamblea Nacional para la protección de militares y civiles que colaboren o hayan colaborado con la restitución del orden constitucional]
theme: jekyll-theme-minimal
logo: [https://www.onlinestores.com/flagdetective/images/download/venezuela-hi.jpg]
